# Generated by Django 2.1.7 on 2019-03-10 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
