# Generated by Django 2.1.7 on 2019-05-18 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semana')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('T', 'Teorica'), ('P', 'Pratica'), ('-', 'Nenhum')], max_length=1, verbose_name='Tipo')),
                ('conteudo', models.CharField(max_length=100, verbose_name='Conteudo')),
            ],
            options={
                'ordering': ('conteudo',),
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Competencia')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Conteudo')),
                ('modulo', models.CharField(max_length=1, verbose_name='Modulo')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Curso')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDisciplinaCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Competencia')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDisciplinaHabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDisciplinaLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDisciplinaObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('tipo', models.CharField(choices=[('T', 'Teorica'), ('P', 'Pratica')], max_length=1, verbose_name='Tipo')),
                ('creditos', models.IntegerField(verbose_name='Creditos')),
                ('ementa', models.CharField(max_length=1000, null=True, verbose_name='Ementa')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Habilidade')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=500, verbose_name='Autor(es)')),
                ('bibliografia', models.CharField(choices=[('B', 'Basica'), ('C', 'Complementar')], max_length=1, verbose_name='Bibliografia')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MetodologiaEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Metodologia de Ensino')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Objetivo')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('tipo', models.CharField(choices=[('A', 'Administrador'), ('C', 'Coordenador'), ('P', 'Professor')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'ordering': ('usuario',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('semestre', models.CharField(max_length=10, null=True, verbose_name='Semestre')),
                ('recursos', models.CharField(max_length=200, null=True, verbose_name='Recursos')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.AddField(
            model_name='cursodisciplinaobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Objetivo'),
        ),
        migrations.AddField(
            model_name='cursodisciplinalivro',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Livro'),
        ),
        migrations.AddField(
            model_name='cursodisciplinahabilidade',
            name='habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Habilidade'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='competencias',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaCompetencia', to='admFacens.Competencia'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Disciplina'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='habilidades',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaHabilidade', to='admFacens.Habilidade'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='livros',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaLivro', to='admFacens.Livro'),
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='objetivos',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaObjetivo', to='admFacens.Objetivo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(through='admFacens.CursoDisciplina', to='admFacens.Disciplina'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='cursoDisciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Turma'),
        ),
    ]
