# Generated by Django 2.1.7 on 2019-03-10 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Objetivo')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='semestre',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano'),
        ),
    ]
