# Generated by Django 2.1.7 on 2019-04-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='cursoDisciplina',
        ),
    ]
