# Generated by Django 2.1.7 on 2019-04-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0002_auto_20190406_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso'),
        ),
    ]
