# Generated by Django 2.1.7 on 2019-03-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivos',
            field=models.ManyToManyField(through='admFacens.CursoObjetivo', to='admFacens.Objetivo'),
        ),
    ]
