# Generated by Django 2.1.7 on 2019-05-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0003_auto_20190428_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='objetivos',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaObjetivo', to='admFacens.Objetivo'),
        ),
    ]
