# Generated by Django 2.1.7 on 2019-05-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0004_auto_20190504_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Competencia')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='competencias',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaCompetencia', to='admFacens.Competencia'),
        ),
    ]
