# Generated by Django 2.1.7 on 2019-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0004_habilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Curso')),
                ('description', models.CharField(max_length=1000, verbose_name='Descricao')),
                ('semestres', models.ManyToManyField(to='admFacens.Semestre')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
