# Generated by Django 2.1.7 on 2019-03-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0004_auto_20190316_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Competencia')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoHabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Habilidade')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='competencias',
            field=models.ManyToManyField(through='admFacens.CursoCompetencia', to='admFacens.Competencia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='habilidades',
            field=models.ManyToManyField(through='admFacens.CursoHabilidade', to='admFacens.Habilidade'),
        ),
    ]
