# Generated by Django 2.1.7 on 2019-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0005_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='competencias',
            field=models.ManyToManyField(to='admFacens.Competencia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='habilidades',
            field=models.ManyToManyField(to='admFacens.Habilidade'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivos',
            field=models.ManyToManyField(to='admFacens.Objetivo'),
        ),
    ]
