# Generated by Django 2.1.7 on 2019-05-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0005_auto_20190504_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaHabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Habilidade')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='habilidades',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaHabilidade', to='admFacens.Habilidade'),
        ),
    ]
