# Generated by Django 2.1.7 on 2019-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0005_auto_20190406_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='creditos',
            field=models.IntegerField(verbose_name='Creditos'),
        ),
    ]
