# Generated by Django 2.1.7 on 2019-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0006_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='creditos',
            field=models.IntegerField(choices=[(1, 2), (2, 4), (3, 6), (4, 8)], verbose_name='Creditos'),
        ),
    ]
