# Generated by Django 2.1.7 on 2019-05-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0007_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodologiaEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Metodologia de Ensino')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
    ]
