# Generated by Django 2.1.7 on 2019-05-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0008_metodologiaensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ementa'),
        ),
    ]
