# Generated by Django 2.1.7 on 2019-03-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0008_auto_20190316_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='objetivos',
            field=models.ManyToManyField(to='admFacens.CursoObjetivo'),
        ),
    ]
