# Generated by Django 2.1.7 on 2019-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0009_cursodisciplina_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='competencias',
            field=models.ManyToManyField(to='admFacens.Competencia'),
        ),
    ]
