# Generated by Django 2.1.7 on 2019-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0009_disciplina_ementa'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.CharField(max_length=10, null=True, verbose_name='Semestre'),
        ),
    ]
