# Generated by Django 2.1.7 on 2019-05-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0010_turma_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='recursos',
            field=models.CharField(max_length=200, null=True, verbose_name='Recursos'),
        ),
    ]
