# Generated by Django 2.1.7 on 2019-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0010_cursodisciplina_competencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursodisciplina',
            name='competencias',
            field=models.ManyToManyField(to='admFacens.CursoCompetencia'),
        ),
    ]
