# Generated by Django 2.1.7 on 2019-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0011_auto_20190317_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='habilidades',
            field=models.ManyToManyField(to='admFacens.CursoHabilidade'),
        ),
    ]
