# Generated by Django 2.1.7 on 2019-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0012_cursodisciplina_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='competencias',
            field=models.ManyToManyField(blank=True, to='admFacens.CursoCompetencia'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='admFacens.CursoHabilidade'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='objetivos',
            field=models.ManyToManyField(blank=True, to='admFacens.CursoObjetivo'),
        ),
    ]
