# Generated by Django 2.1.7 on 2019-03-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0013_auto_20190317_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='turmas',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaTurma', to='admFacens.Turma'),
        ),
    ]
