# Generated by Django 2.1.7 on 2019-03-17 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0014_auto_20190317_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semana')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('T', 'Teorica'), ('P', 'Pratica'), ('-', 'Nenhum')], max_length=1, verbose_name='Tipo')),
                ('conteudo', models.CharField(max_length=100, verbose_name='Conteudo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('codigo',)},
        ),
    ]
