# Generated by Django 2.1.7 on 2019-03-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0015_auto_20190317_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaTurmaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Aula')),
                ('cursoDisciplinaTurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplinaTurma')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplinaturma',
            name='aulas',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaTurmaAula', to='admFacens.Aula'),
        ),
    ]
