# Generated by Django 2.1.7 on 2019-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0016_auto_20190317_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=500, verbose_name='Autor(es)')),
                ('bibliografia', models.CharField(choices=[('B', 'Basica'), ('C', 'Complementar')], max_length=1, verbose_name='Bibliografia')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('conteudo',)},
        ),
    ]
