# Generated by Django 2.1.7 on 2019-03-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0017_auto_20190317_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplinaLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.CursoDisciplina')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Livro')),
            ],
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='livros',
            field=models.ManyToManyField(through='admFacens.CursoDisciplinaLivro', to='admFacens.Livro'),
        ),
    ]
