# Generated by Django 2.1.7 on 2019-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0018_auto_20190317_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplinaturmaaula',
            name='livros',
            field=models.ManyToManyField(to='admFacens.CursoDisciplinaLivro'),
        ),
    ]
