# Generated by Django 2.1.7 on 2019-03-31 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admFacens', '0020_auto_20190331_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoobjetivo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Curso'),
        ),
        migrations.AlterField(
            model_name='cursoobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admFacens.Objetivo'),
        ),
    ]
